name: Element.unselectable
author: marcelo.origoni
category: Native
tags: [element, unselectable, non selectable]
docs: http://marcelo.origoni.com.ar/Element.unselectable/
demo: http://marcelo.origoni.com.ar/Element.unselectable/demo.php
current: 1.0